### PR TITLE
Improve frozen frontend handling

### PR DESCRIPTION
**Pull request by dmolineus**
This pull request improves the frozen frontend handling. Instead of hiding the survey it is visible but only a message it's shown that the form is not frozend and the submit button is hidden.

### CODE REVIEW

**Comment by m-vo** [comment]
Isn't it better to prevent a non-frozen form from being displayed? You can still disable `prevent_editing` and use it with no data integrity protection during development, can't you?

But I'm not sure I fully understand the problem. :smiley:  When would you need this?

**Comment by dmolineus** [comment]
This is meant for editors which want to see how the survey looks like in the frontend. I don't want to disable `prevent_editing` for that case. Maybe we can bind it to the preview mode of Contao but not sure if it's better.

**Comment by m-vo** [comment]
Got it.

> Maybe we can bind it to the preview mode of Contao 

This would be a nice way, maybe even only if "show hidden" is selected. I'm not quite sure how to build this. But if it's feasible without too much work, I'd prefer this. 

Right now I am overwriting the `_frozen.html.twig` template with an empty one in my application  because I do not want to show anything if a survey was not frozen. Would be nice, if I could  keep that behavior.

**Comment by dmolineus** [comment]
I reworked the implementation so that the not frozen survey is only shown in the preview mode (`preview.php` and `show hidden elements` enabled). Then the submit button is hidden. In every other case the behaviour is like before.

**Comment by m-vo** [comment]
LGTM, just needs a rebase.

**Comment by dmolineus** [comment]
> LGTM, just needs a rebase.

Done.

**Review by m-vo — APPROVED** [review]

**Comment by m-vo** [comment]
Thanks @dmolineus. :tada:

**Pull request merged**
